// Sample movies data based on IMDb Top 250
// This file can be used to seed the database with initial movie data

const sampleMovies = [
  {
    title: "The Shawshank Redemption",
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    rating: 9.3,
    releaseDate: "1994-09-23",
    duration: 142,
    director: "Frank Darabont",
    genre: ["Drama"],
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
    imdbId: "tt0111161"
  },
  {
    title: "The Godfather",
    description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    rating: 9.2,
    releaseDate: "1972-03-24",
    duration: 175,
    director: "Francis Ford Coppola",
    genre: ["Crime", "Drama"],
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    imdbId: "tt0068646"
  },
  {
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    rating: 9.0,
    releaseDate: "2008-07-18",
    duration: 152,
    director: "Christopher Nolan",
    genre: ["Action", "Crime", "Drama"],
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg",
    imdbId: "tt0468569"
  },
  {
    title: "Pulp Fiction",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    rating: 8.9,
    releaseDate: "1994-10-14",
    duration: 154,
    director: "Quentin Tarantino",
    genre: ["Crime", "Drama"],
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    imdbId: "tt0110912"
  },
  {
    title: "Forrest Gump",
    description: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
    rating: 8.8,
    releaseDate: "1994-07-06",
    duration: 142,
    director: "Robert Zemeckis",
    genre: ["Drama", "Romance"],
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    imdbId: "tt0109830"
  },
  {
    title: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    rating: 8.8,
    releaseDate: "2010-07-16",
    duration: 148,
    director: "Christopher Nolan",
    genre: ["Action", "Sci-Fi", "Thriller"],
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg",
    imdbId: "tt1375666"
  },
  {
    title: "The Matrix",
    description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    rating: 8.7,
    releaseDate: "1999-03-31",
    duration: 136,
    director: "Lana Wachowski, Lilly Wachowski",
    genre: ["Action", "Sci-Fi"],
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    imdbId: "tt0133093"
  },
  {
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    rating: 8.6,
    releaseDate: "2014-11-07",
    duration: 169,
    director: "Christopher Nolan",
    genre: ["Adventure", "Drama", "Sci-Fi"],
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    imdbId: "tt0816692"
  },
  {
    title: "Gladiator",
    description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    rating: 8.5,
    releaseDate: "2000-05-05",
    duration: 155,
    director: "Ridley Scott",
    genre: ["Action", "Adventure", "Drama"],
    cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    imdbId: "tt0172495"
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    description: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    rating: 9.0,
    releaseDate: "2003-12-17",
    duration: 201,
    director: "Peter Jackson",
    genre: ["Adventure", "Drama", "Fantasy"],
    cast: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    imdbId: "tt0167260"
  },
  {
    title: "Fight Club",
    description: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    rating: 8.8,
    releaseDate: "1999-10-15",
    duration: 139,
    director: "David Fincher",
    genre: ["Drama"],
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
    imdbId: "tt0137523"
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    rating: 8.8,
    releaseDate: "2001-12-19",
    duration: 178,
    director: "Peter Jackson",
    genre: ["Adventure", "Drama", "Fantasy"],
    cast: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_.jpg",
    imdbId: "tt0120737"
  },
  {
    title: "Star Wars: Episode V - The Empire Strikes Back",
    description: "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda.",
    rating: 8.7,
    releaseDate: "1980-06-20",
    duration: 124,
    director: "Irvin Kershner",
    genre: ["Action", "Adventure", "Fantasy"],
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYmU1NDRjNDgtMzhiMi00NjZmLTg5NGItZDNiZjU5NTU4OTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    imdbId: "tt0080684"
  },
  {
    title: "The Lord of the Rings: The Two Towers",
    description: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman.",
    rating: 8.8,
    releaseDate: "2002-12-18",
    duration: 179,
    director: "Peter Jackson",
    genre: ["Adventure", "Drama", "Fantasy"],
    cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    imdbId: "tt0167261"
  },
  {
    title: "Goodfellas",
    description: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.",
    rating: 8.7,
    releaseDate: "1990-09-19",
    duration: 146,
    director: "Martin Scorsese",
    genre: ["Biography", "Crime", "Drama"],
    cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    imdbId: "tt0099685"
  },
  {
    title: "Seven Samurai",
    description: "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.",
    rating: 8.6,
    releaseDate: "1954-04-26",
    duration: 207,
    director: "Akira Kurosawa",
    genre: ["Action", "Drama"],
    cast: ["Toshirô Mifune", "Takashi Shimura", "Keiko Tsushima"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNWQ3OTM4ZGItMWEwZi00MjI5LWI3YzgtNTYwNWRkNmIzMGI5XkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_.jpg",
    imdbId: "tt0047478"
  },
  {
    title: "Se7en",
    description: "Two detectives hunt a serial killer who uses the seven deadly sins as his motives.",
    rating: 8.6,
    releaseDate: "1995-09-22",
    duration: 127,
    director: "David Fincher",
    genre: ["Crime", "Drama", "Mystery"],
    cast: ["Morgan Freeman", "Brad Pitt", "Kevin Spacey"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    imdbId: "tt0114369"
  },
  {
    title: "The Silence of the Lambs",
    description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
    rating: 8.6,
    releaseDate: "1991-02-14",
    duration: 118,
    director: "Jonathan Demme",
    genre: ["Crime", "Drama", "Thriller"],
    cast: ["Jodie Foster", "Anthony Hopkins", "Lawrence A. Bonney"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    imdbId: "tt0102926"
  },
  {
    title: "Saving Private Ryan",
    description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
    rating: 8.6,
    releaseDate: "1998-07-24",
    duration: 169,
    director: "Steven Spielberg",
    genre: ["Drama", "War"],
    cast: ["Tom Hanks", "Matt Damon", "Tom Sizemore"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg",
    imdbId: "tt0120815"
  },
  {
    title: "City of God",
    description: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
    rating: 8.6,
    releaseDate: "2002-08-30",
    duration: 130,
    director: "Fernando Meirelles",
    genre: ["Crime", "Drama"],
    cast: ["Alexandre Rodrigues", "Leandro Firmino", "Matheus Nachtergaele"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BOTMwYjc5ZmItYTFjZC00ZGQ3LTlkNTMtMjZiNTZlMWQzNzI5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    imdbId: "tt0317248"
  },
  {
    title: "Spirited Away",
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
    rating: 8.6,
    releaseDate: "2001-07-20",
    duration: 125,
    director: "Hayao Miyazaki",
    genre: ["Animation", "Adventure", "Family"],
    cast: ["Daveigh Chase", "Suzanne Pleshette", "Miyu Irino"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    imdbId: "tt0245429"
  },
  {
    title: "Life Is Beautiful",
    description: "When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son.",
    rating: 8.6,
    releaseDate: "1997-12-20",
    duration: 116,
    director: "Roberto Benigni",
    genre: ["Comedy", "Drama", "Romance"],
    cast: ["Roberto Benigni", "Nicoletta Braschi", "Giorgio Cantarini"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTJiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    imdbId: "tt0118799"
  },
  {
    title: "The Green Mile",
    description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
    rating: 8.6,
    releaseDate: "1999-12-10",
    duration: 189,
    director: "Frank Darabont",
    genre: ["Crime", "Drama", "Fantasy"],
    cast: ["Tom Hanks", "Michael Clarke Duncan", "David Morse"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_.jpg",
    imdbId: "tt0120689"
  },
  {
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    rating: 8.5,
    releaseDate: "2019-05-30",
    duration: 132,
    director: "Bong Joon Ho",
    genre: ["Comedy", "Drama", "Thriller"],
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg",
    imdbId: "tt6751668"
  },
  {
    title: "The Departed",
    description: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
    rating: 8.5,
    releaseDate: "2006-10-06",
    duration: 151,
    director: "Martin Scorsese",
    genre: ["Crime", "Drama", "Thriller"],
    cast: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_.jpg",
    imdbId: "tt0407887"
  },
  {
    title: "Whiplash",
    description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    rating: 8.5,
    releaseDate: "2014-10-10",
    duration: 106,
    director: "Damien Chazelle",
    genre: ["Drama", "Music"],
    cast: ["Miles Teller", "J.K. Simmons", "Melissa Benoist"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    imdbId: "tt2582802"
  },
  {
    title: "The Prestige",
    description: "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
    rating: 8.5,
    releaseDate: "2006-10-20",
    duration: 130,
    director: "Christopher Nolan",
    genre: ["Drama", "Mystery", "Sci-Fi"],
    cast: ["Christian Bale", "Hugh Jackman", "Scarlett Johansson"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_.jpg",
    imdbId: "tt0482571"
  },
  {
    title: "The Lion King",
    description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    rating: 8.5,
    releaseDate: "1994-06-24",
    duration: 88,
    director: "Roger Allers, Rob Minkoff",
    genre: ["Animation", "Adventure", "Drama"],
    cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_.jpg",
    imdbId: "tt0110357"
  },
  {
    title: "Back to the Future",
    description: "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean.",
    rating: 8.5,
    releaseDate: "1985-07-03",
    duration: 116,
    director: "Robert Zemeckis",
    genre: ["Adventure", "Comedy", "Sci-Fi"],
    cast: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    imdbId: "tt0088763"
  },
  {
    title: "Terminator 2: Judgment Day",
    description: "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son from a more advanced and powerful cyborg.",
    rating: 8.5,
    releaseDate: "1991-07-03",
    duration: 137,
    director: "James Cameron",
    genre: ["Action", "Sci-Fi"],
    cast: ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    imdbId: "tt0103064"
  },
  {
    title: "American History X",
    description: "A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.",
    rating: 8.5,
    releaseDate: "1998-10-30",
    duration: 119,
    director: "Tony Kaye",
    genre: ["Crime", "Drama"],
    cast: ["Edward Norton", "Edward Furlong", "Beverly D'Angelo"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZjA0MTM4MTQtNzY5MC00NzY3LWI1ZTgtYzcxMjkyMzU4MDZiXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg",
    imdbId: "tt0120586"
  },
  {
    title: "Modern Times",
    description: "The Tramp struggles to live in modern industrial society with the help of a young homeless woman.",
    rating: 8.5,
    releaseDate: "1936-02-25",
    duration: 87,
    director: "Charles Chaplin",
    genre: ["Comedy", "Drama", "Romance"],
    cast: ["Charles Chaplin", "Paulette Goddard", "Henry Bergman"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYjJiZjMzYzktNjU0NS00OTkxLWEwYzItYzdhYWJjN2QzMTRlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    imdbId: "tt0027977"
  },
  {
    title: "Psycho",
    description: "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.",
    rating: 8.5,
    releaseDate: "1960-09-08",
    duration: 109,
    director: "Alfred Hitchcock",
    genre: ["Horror", "Mystery", "Thriller"],
    cast: ["Anthony Perkins", "Janet Leigh", "Vera Miles"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    imdbId: "tt0054215"
  },
  {
    title: "The Pianist",
    description: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
    rating: 8.5,
    releaseDate: "2002-09-25",
    duration: 150,
    director: "Roman Polanski",
    genre: ["Biography", "Drama", "Music"],
    cast: ["Adrien Brody", "Thomas Kretschmann", "Frank Finlay"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    imdbId: "tt0253474"
  },
  {
    title: "Léon: The Professional",
    description: "12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered.",
    rating: 8.5,
    releaseDate: "1994-11-18",
    duration: 110,
    director: "Luc Besson",
    genre: ["Action", "Crime", "Drama"],
    cast: ["Jean Reno", "Gary Oldman", "Natalie Portman"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BODllNWE0MmEtYjUwZi00ZjY3LThmNmQtZjZlMjI2YTZjYmQ0XkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_.jpg",
    imdbId: "tt0110413"
  },
  {
    title: "The Usual Suspects",
    description: "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.",
    rating: 8.5,
    releaseDate: "1995-08-16",
    duration: 106,
    director: "Bryan Singer",
    genre: ["Crime", "Drama", "Mystery"],
    cast: ["Kevin Spacey", "Gabriel Byrne", "Chazz Palminteri"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    imdbId: "tt0114814"
  },
  {
    title: "Casablanca",
    description: "A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.",
    rating: 8.5,
    releaseDate: "1942-11-26",
    duration: 102,
    director: "Michael Curtiz",
    genre: ["Drama", "Romance", "War"],
    cast: ["Humphrey Bogart", "Ingrid Bergman", "Paul Henreid"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg",
    imdbId: "tt0034583"
  },
  {
    title: "Django Unchained",
    description: "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.",
    rating: 8.4,
    releaseDate: "2012-12-25",
    duration: 165,
    director: "Quentin Tarantino",
    genre: ["Drama", "Western"],
    cast: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_.jpg",
    imdbId: "tt1853728"
  },
  {
    title: "WALL·E",
    description: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
    rating: 8.4,
    releaseDate: "2008-06-27",
    duration: 98,
    director: "Andrew Stanton",
    genre: ["Animation", "Adventure", "Family"],
    cast: ["Ben Burtt", "Elissa Knight", "Jeff Garlin"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_.jpg",
    imdbId: "tt0910970"
  },
  {
    title: "The Lives of Others",
    description: "In 1984 East Berlin, an agent of the secret police conducting surveillance on a writer and his lover finds himself becoming increasingly absorbed by their lives.",
    rating: 8.4,
    releaseDate: "2006-03-23",
    duration: 137,
    director: "Florian Henckel von Donnersmarck",
    genre: ["Drama", "Mystery", "Thriller"],
    cast: ["Ulrich Mühe", "Martina Gedeck", "Sebastian Koch"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNmQyNmJjM2ItNTQzYi00ZjMxLWFjMDYtZjUyN2YzOGJjMzgxXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
    imdbId: "tt0405094"
  },
  {
    title: "Paths of Glory",
    description: "After refusing to attack an enemy position, a general accuses the soldiers of cowardice and their commanding officer must defend them.",
    rating: 8.4,
    releaseDate: "1957-12-25",
    duration: 88,
    director: "Stanley Kubrick",
    genre: ["Drama", "War"],
    cast: ["Kirk Douglas", "Ralph Meeker", "Adolphe Menjou"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BOTI5Nzc0OTMtYzBkMS00NjkxLThmM2UtNjM2ODgxN2M5NjNkXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_.jpg",
    imdbId: "tt0050825"
  },
  {
    title: "The Shining",
    description: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.",
    rating: 8.4,
    releaseDate: "1980-05-23",
    duration: 146,
    director: "Stanley Kubrick",
    genre: ["Drama", "Horror"],
    cast: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    imdbId: "tt0081505"
  },
  {
    title: "Avengers: Infinity War",
    description: "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos.",
    rating: 8.4,
    releaseDate: "2018-04-27",
    duration: 149,
    director: "Anthony Russo, Joe Russo",
    genre: ["Action", "Adventure", "Sci-Fi"],
    cast: ["Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_.jpg",
    imdbId: "tt4154756"
  },
  {
    title: "Witness for the Prosecution",
    description: "A veteran British barrister must defend his client in a murder trial that has surprise after surprise.",
    rating: 8.4,
    releaseDate: "1957-12-17",
    duration: 116,
    director: "Billy Wilder",
    genre: ["Crime", "Drama", "Mystery"],
    cast: ["Tyrone Power", "Marlene Dietrich", "Charles Laughton"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNDQwODU5OWYtNDcyNi00MDQ1LThiOGMtZDkwNWJiM2Y3MDg0XkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_.jpg",
    imdbId: "tt0051201"
  },
  {
    title: "Alien",
    description: "After investigating a mysterious transmission of unknown origin, the crew of a commercial spacecraft encounters a deadly lifeform.",
    rating: 8.4,
    releaseDate: "1979-06-22",
    duration: 117,
    director: "Ridley Scott",
    genre: ["Horror", "Sci-Fi"],
    cast: ["Sigourney Weaver", "Tom Skerritt", "John Hurt"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
    imdbId: "tt0078748"
  },
  {
    title: "Spider-Man: Into the Spider-Verse",
    description: "Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions.",
    rating: 8.4,
    releaseDate: "2018-12-14",
    duration: 117,
    director: "Bob Persichetti, Peter Ramsey",
    genre: ["Animation", "Action", "Adventure"],
    cast: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_.jpg",
    imdbId: "tt4633694"
  },
  {
    title: "Dr. Strangelove",
    description: "An insane American general orders a bombing attack on the Soviet Union, triggering a path to nuclear holocaust.",
    rating: 8.4,
    releaseDate: "1964-01-29",
    duration: 95,
    director: "Stanley Kubrick",
    genre: ["Comedy", "War"],
    cast: ["Peter Sellers", "George C. Scott", "Sterling Hayden"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    imdbId: "tt0057012"
  },
  {
    title: "Oldboy",
    description: "After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days.",
    rating: 8.4,
    releaseDate: "2003-11-21",
    duration: 120,
    director: "Park Chan-wook",
    genre: ["Action", "Drama", "Mystery"],
    cast: ["Choi Min-sik", "Yoo Ji-tae", "Kang Hye-jeong"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTI3NTQyMzU5M15BMl5BanBnXkFtZTcwMTM2MjgyMQ@@._V1_.jpg",
    imdbId: "tt0364569"
  },
  {
    title: "Coco",
    description: "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather.",
    rating: 8.4,
    releaseDate: "2017-11-22",
    duration: 105,
    director: "Lee Unkrich, Adrian Molina",
    genre: ["Animation", "Adventure", "Comedy"],
    cast: ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_.jpg",
    imdbId: "tt2380307"
  },
  {
    title: "Amadeus",
    description: "The life, success and troubles of Wolfgang Amadeus Mozart, as told by Antonio Salieri, the contemporaneous composer who was deeply jealous of Mozart's talent.",
    rating: 8.4,
    releaseDate: "1984-09-19",
    duration: 160,
    director: "Miloš Forman",
    genre: ["Biography", "Drama", "Music"],
    cast: ["F. Murray Abraham", "Tom Hulce", "Elizabeth Berridge"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNWJlNzUzNGMtYTAwMS00ZjI2LWFmNWQtODcxNWUxODA5YmU1XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
    imdbId: "tt0086879"
  },
  {
    title: "Once Upon a Time in the West",
    description: "A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin.",
    rating: 8.5,
    releaseDate: "1968-12-21",
    duration: 165,
    director: "Sergio Leone",
    genre: ["Western"],
    cast: ["Henry Fonda", "Charles Bronson", "Claudia Cardinale"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BODQ3NDExOGYtMzI3Mi00NWRlLTkwNjAtNjc4MDgzZGJiZTA1XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
    imdbId: "tt0064116"
  },
  {
    title: "Toy Story",
    description: "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
    rating: 8.3,
    releaseDate: "1995-11-22",
    duration: 81,
    director: "John Lasseter",
    genre: ["Animation", "Adventure", "Comedy"],
    cast: ["Tom Hanks", "Tim Allen", "Don Rickles"],
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_.jpg",
    imdbId: "tt0114709"
  }
];

module.exports = sampleMovies;
